# These are supported funding model platforms

github: [DelphiWorlds]
custom: ["https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=CRMMYFP3QSS68"]
