unit DW.Precompile;

{*******************************************************}
{                                                       }
{                      Kastri                           }
{                                                       }
{         Delphi Worlds Cross-Platform Library          }
{                                                       }
{  Copyright 2020-2026 Dave Nottage under MIT license   }
{  which is located in the root folder of this library  }
{                                                       }
{*******************************************************}

interface

implementation

// This unit is provided for compiler checks *ONLY*, and should not be included in a regular application

uses
{$IF Defined(ANDROID)}
  DW.Androidapi.JNI.AdMob,
  DW.Androidapi.JNI.Android.Util,
  DW.Androidapi.JNI.AndroidX.Activity,
  DW.Androidapi.JNI.AndroidX.App,
  DW.Androidapi.JNI.AndroidX.Biometric,
  DW.Androidapi.JNI.AndroidX.Camera.Lifecycle,
  DW.Androidapi.JNI.AndroidX.Camera,
  DW.Androidapi.JNI.AndroidX.Content,
  DW.Androidapi.JNI.AndroidX.FileProvider,
  DW.Androidapi.JNI.AndroidX.Lifecycle,
  DW.Androidapi.JNI.AndroidX.LocalBroadcastManager,
  DW.Androidapi.JNI.AndroidX.Media3.Common,
  DW.Androidapi.JNI.AndroidX.Media3.Datasource,
  DW.Androidapi.JNI.AndroidX.Media3.Decoder,
  DW.Androidapi.JNI.AndroidX.Media3.Exoplayer,
  DW.Androidapi.JNI.AndroidX.Media3.UI,
  DW.Androidapi.JNI.AndroidX.TvProvider,
  DW.Androidapi.JNI.AndroidX.Wearable,
  DW.Androidapi.JNI.Animation,
  DW.Androidapi.JNI.App,
  DW.Androidapi.JNI.AssetDelivery,
  DW.Androidapi.JNI.Billing,
  DW.Androidapi.JNI.Concurrent,
  DW.Androidapi.JNI.Content,
  DW.Androidapi.JNI.DataCollection,
  DW.Androidapi.JNI.DWBiometricFragmentActivity,
  DW.Androidapi.JNI.DWCameraHelpers,
  DW.Androidapi.JNI.DWFingerprintAuthenticationCallback,
  DW.Androidapi.JNI.DWFirebaseServiceHelpers,
  DW.Androidapi.JNI.DWFusedLocation,
  DW.Androidapi.JNI.DWGenericView,
  DW.Androidapi.JNI.DWGeofence,
  DW.Androidapi.JNI.DWGoogleSignIn,
  DW.Androidapi.JNI.DWMediaProjectionCallback,
  DW.Androidapi.JNI.DWMultiBroadcastReceiver,
  DW.Androidapi.JNI.DWNetworkCallback,
  DW.Androidapi.JNI.DWTimerTask,
  DW.Androidapi.JNI.DWUtility,
  DW.Androidapi.JNI.DWWebChromeClient,
  DW.Androidapi.JNI.EMDK,
  DW.Androidapi.JNI.Firebase,
  DW.Androidapi.JNI.FirebaseAnalytics,
  DW.Androidapi.JNI.GoogleSignIn,
  DW.Androidapi.JNI.Guava,
  DW.Androidapi.JNI.Hardware,
  DW.Androidapi.JNI.Hardware.Camera2,
  DW.Androidapi.JNI.Hardware.Sensor,
  DW.Androidapi.JNI.Hardware.Usb,
  DW.Androidapi.JNI.Icu,
  DW.Androidapi.JNI.Java.Net,
  DW.Androidapi.JNI.JavaTypes,
  DW.Androidapi.JNI.Lang,
  DW.Androidapi.JNI.Location,
  DW.Androidapi.JNI.Net,
  DW.Androidapi.JNI.Nfc,
  DW.Androidapi.JNI.Notification,
  DW.Androidapi.JNI.NotificationListenerService,
  DW.Androidapi.JNI.Os,
  DW.Androidapi.JNI.PlayCore,
  DW.Androidapi.JNI.PlayServices,
  DW.Androidapi.JNI.PlayServices.AppUpdate,
  DW.Androidapi.JNI.Print,
  DW.Androidapi.JNI.Security,
  DW.Androidapi.JNI.SeekBar,
  DW.Androidapi.JNI.SupportV4,
  DW.Androidapi.JNI.Telecom,
  DW.Androidapi.JNI.Util,
  DW.Androidapi.JNI.View,
  DW.Androidapi.JNI.VisionBarcode,
  DW.Androidapi.JNI.Widget.Toast,
  DW.Android.Helpers,
  DW.Android.Service,
  DW.Background.Android,
  DW.ServiceCommander.Android,
  DW.TimerTask.Android,
  DW.Toast.Android,
  DW.WebChromeClient.Android,
{$ENDIF}

{$IF Defined(LINUX64)}
  DW.Linuxapi.Epoll,
  DW.Linuxapi.Timerfd,
  DW.OSDevice.Linux,
{$ENDIF}

{$IF Defined(MACOS)}
  DW.Graphics.Helpers.Mac,
  DW.IOUtils.Helpers.Mac,
  DW.OSLog.Mac,
  DW.OSMetadata.Mac,
  DW.OSTimer.Mac,
  DW.Macapi.Dispatch,
  DW.Macapi.Helpers,
  DW.Macapi.ObjCBlocks,
  DW.Macapi.ObjCRuntime,
{$ENDIF}

{$IF Defined(OSX)}
  DW.Macapi.AppKit,
  // DW.Macapi.AuthenticationServices,
  DW.Macapi.AVFAudio,
  DW.Macapi.AVFoundation,
  DW.Macapi.AVKit,
  DW.Macapi.CloudKit,
  DW.Macapi.CoreAudioTypes,
  DW.Macapi.CoreData,
  DW.Macapi.CoreServices,
  DW.Macapi.CoreSpotlight,
  DW.Macapi.Foundation,
  DW.Macapi.FSEvents,
  DW.Macapi.IOKit,
  DW.Macapi.LocalAuthentication,
  DW.Macapi.MultipeerConnectivity,
  DW.Macapi.NetworkExtension,
  DW.Macapi.Simd,
  DW.Macapi.PDFKit,
  DW.Macapi.QuartzCore,
  DW.Macapi.Speech,
  // DW.Macapi.StoreKit,
  DW.Macapi.Symbols,
  // DW.Macapi.SystemConfiguration,
  DW.Macapi.UniformTypeIdentifiers,
  DW.Menus.Mac,
  DW.OSEvents.Mac,
  DW.OSPower.Mac,
  DW.RunProcess.Mac,
  DW.StatusBarMenu.Mac,
{$ENDIF}

{$IF Defined(IOS)}
  DW.AuthenticationServices.iOS,
  DW.iOSapi.AppTrackingTransparency,
  DW.iOSapi.ARKit,
  DW.iOSapi.AuthenticationServices,
  DW.iOSapi.AVFoundation,
  DW.iOSapi.CallKit,
  DW.iOSapi.CarPlay,
  DW.iOSapi.Contacts,
  DW.iOSapi.CoreImage,
  DW.iOSapi.CoreML,
  DW.iOSapi.CoreNFC,
  DW.iOSapi.CoreVideo,
  DW.iOSapi.DeviceCheck,
  DW.iOSapi.EventKit,
  DW.iOSapi.EventKitExtra,
  DW.iOSapi.FBAudienceNetwork,
  DW.iOSapi.Firebase,
  DW.iOSapi.FirebaseAnalytics,
  DW.iOSapi.FirebaseAuth,
  DW.iOSapi.FirebaseCore,
  DW.iOSapi.Foundation,
  DW.iOSapi.GoogleSignIn,
  DW.iOSapi.Helpers,
  DW.iOSapi.ImageIO,
  DW.iOSapi.Intents,
  DW.iOSapi.IOSurface,
  DW.iOSapi.JavaScriptCore,
  DW.iOSapi.MediaPlayer,
  DW.iOSapi.MediaPlayerExtra,
  DW.iOSapi.Messages,
  DW.iOSapi.MessageUI,
  DW.iOSapi.Metal,
  DW.iOSapi.MLKitBarcodeScanning,
  DW.iOSapi.MLKitCommon,
  DW.iOSapi.MLKitVision,
  DW.iOSapi.Network,
  DW.iOSapi.NetworkExtension,
  DW.iOSapi.PassKit,
  DW.iOSapi.PDFKit,
  DW.iOSapi.Photos,
  DW.iOSapi.PhotosUI,
  DW.iOSapi.PushKit,
  DW.iOSapi.QuickLook,
  DW.iOSapi.SceneKit,
  DW.iOSapi.Speech,
  DW.iOSapi.SpriteKit,
  DW.iOSapi.SpriteKitExtra,
  DW.iOSapi.SystemConfiguration,
  {$IF CompilerVersion < 37} 
  DW.iOSapi.UIKit, 
  {$ENDIF}
  DW.iOSapi.UIKitExtra,
  DW.iOSapi.UserNotifications,
  DW.iOSapi.Vision,
  DW.iOSapi.VisionKit,
  DW.Location.iOS,
  DW.MuteCheck,
  DW.MuteCheck.iOS,
  DW.NativeButton.iOS,
  DW.NativeImage.iOS,
  DW.NativeShape.iOS,
  DW.NativeSlider.iOS,
  DW.Orientation.iOS,
  DW.OSPower.iOS,
  // DW.PushNotification.iOS,
  DW.QuickLook.iOS,
  DW.UIHelper.iOS,
  DW.UserDefaults.iOS,
{$ENDIF}

{$IF Defined(POSIX)}
  DW.IOUtils.Helpers.Posix,
  DW.OSDevice.Posix,
{$ENDIF}

{$IF Defined(MSWINDOWS)}
  DW.ADB,
  DW.Connectivity.Win,
  DW.ExternalDevice.Win,
  DW.FileVersionInfo.Win,
  DW.IOUtils.Helpers.Win,
  DW.JavaScript.WebView2,
  DW.NativeImage.Win,
  DW.OSDevice.Win,
  DW.OSLog.Win,
  DW.OSMetadata.Win,
  DW.OSPower.Win,
  DW.OSTimer.Win,
  DW.RunProcess.Win,
  DW.Swizzler.Win,
  DW.Vcl.DialogService,
  DW.Vcl.FormStates,
  DW.Vcl.ListBoxHelper,
  DW.Winapi.ExternalDevice,
  DW.Winapi.Helpers,
  DW.Winapi.NetworkList_TLB,
{$ENDIF}

  // Platform agnostic
  {$IF Defined(MACOS) or Defined(ANDROID)}
  DW.SoundPlayer,
  {$ENDIF}

  {$IF Defined(IOS) or Defined(ANDROID)}
  DW.AdMob,
  DW.AdMobAds,
  DW.BarcodeReader,
  DW.Camera,
  DW.Connectivity,
  DW.Proximity,
  DW.VideoPlayer,
  {$ENDIF}

  {$IF Defined(ANDROID)}
  DW.SymbolScanner,
  {$ENDIF}

  DW.AppReview,
  DW.AppUpdate,
  DW.AudioPlayer,
  DW.AuthenticationServices.Types,
  DW.Base64.Helpers,
  DW.Biometric,
  DW.Classes.Helpers,
  DW.Consts.Android, // Special case
  DW.Consts,
  DW.Controls.Helpers,
  DW.DataGraphics.Helpers,
  DW.DialogService,
  DW.ElasticLayout,
  DW.FilesSelector,
  DW.FileWriter,
  DW.FCMManager,
  DW.Geodetic,
  DW.Geofence,
  DW.Graphics.Helpers,
  DW.ImagePan,
  DW.JavaScript,
  DW.JsonConfig,
  DW.Location,
  DW.MediaLibrary,
  DW.Messaging,
  DW.NativeButton,
  DW.NativeImage,
  DW.NativeShape,
  DW.NativeSlider,
  DW.NFC,
  DW.Notifications,
  DW.OSDevice,
  DW.OSLog,
  DW.OSMetadata,
  DW.OSPower,
  DW.OSTimer,
  DW.PDFControl,
  DW.Permissions.Helpers,
  DW.Printing,
  DW.PushUDP,
  DW.REST.Json.Helpers,
  DW.RunProcess,
  DW.Sensors,
  DW.Services,
  DW.ShareItems,
  DW.SMS,
  DW.SpeechRecognition,
  DW.StartUpCopy,
  DW.SysUtils.Helpers,
  DW.TextToSpeech,
  DW.ThreadedTimer,
  DW.Tokenizers,
  DW.Types.Helpers,
  DW.Types,
  DW.UIHelper,
  DW.UniversalLinks,
  DW.VirtualKeyboard.Helpers,
  DW.VKVertScrollbox,
  DW.WebBrowserExt;

end.
